/* ───────────────────────────────────────────────────────────────────────────
 * scorecard-data.js — GENERATED by tools/build-scorecard.js. Do not hand-edit
 * PF_SCORECARD or PF_PREDICTIONS (PF_GRADED is the one exception — see below).
 * Regenerate:  node tools/build-scorecard.js
 *
 * PF_SCORECARD: every historical quarter across every thesis's TRACK_ALL, with whether
 * price landed inside some band ("bandHit"). These are backtest-reconstructed quarters
 * (see CLAUDE.md data-freshness rules) — high band-hit rates here mostly reflect bands
 * chosen to explain what already happened, not a forward-looking track record.
 *
 * PF_PREDICTIONS: the CURRENT standing "most-likely case" per ticker, taken verbatim from
 * that stock's own QUARTERLY-UPDATE-CHECKLIST.md log (real, already-recorded judgment).
 * This is what /scorecard grades against once each stock's NEXT /update-thesis appends a
 * new TRACK_ALL entry — that comparison is the only honest, non-hindsight-biased number
 * this system can produce, and it starts at zero rows until that happens for real.
 * ─────────────────────────────────────────────────────────────────────────── */

const PF_SCORECARD = [
  {
    "t": "ALAB",
    "quarter": "Q3 24",
    "date": "2024-11",
    "post": 55,
    "landed": "base",
    "conf": "low",
    "bandHit": true
  },
  {
    "t": "ALAB",
    "quarter": "Q4 24",
    "date": "2025-02",
    "post": 75,
    "landed": "base",
    "conf": "low",
    "bandHit": true
  },
  {
    "t": "ALAB",
    "quarter": "Q1 25",
    "date": "2025-05",
    "post": 70,
    "landed": "bear→base",
    "conf": "low",
    "bandHit": true
  },
  {
    "t": "ALAB",
    "quarter": "Q2 25",
    "date": "2025-08",
    "post": 100,
    "landed": "base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "ALAB",
    "quarter": "Q3 25",
    "date": "2025-11",
    "post": 160,
    "landed": "base→bull",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "ALAB",
    "quarter": "Q4 25",
    "date": "2026-02",
    "post": 215,
    "landed": "base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "ALAB",
    "quarter": "Q1 26",
    "date": "2026-05",
    "post": 300,
    "landed": "base→bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "AMZN",
    "quarter": "Q4 2024",
    "date": "2025-02",
    "post": 212,
    "landed": "bear",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "AMZN",
    "quarter": "Q1 2025",
    "date": "2025-05",
    "post": 192,
    "landed": "bear",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "AMZN",
    "quarter": "Q2 2025",
    "date": "2025-08",
    "post": 222,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "AMZN",
    "quarter": "Q3 2025",
    "date": "2025-10",
    "post": 236,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "AMZN",
    "quarter": "Q4 2025",
    "date": "2026-02",
    "post": 256,
    "landed": "base→bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "AMZN",
    "quarter": "Q1 2026",
    "date": "2026-04",
    "post": 232,
    "landed": "bear→base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "ASML",
    "quarter": "Q4 2024",
    "date": "2025-01",
    "post": 770,
    "landed": "base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "ASML",
    "quarter": "Q1 2025",
    "date": "2025-04",
    "post": 800,
    "landed": "base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "ASML",
    "quarter": "Q2 2025",
    "date": "2025-07",
    "post": 710,
    "landed": "bear→base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "ASML",
    "quarter": "Q3 2025",
    "date": "2025-10",
    "post": 875,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "ASML",
    "quarter": "Q4 2025",
    "date": "2026-01",
    "post": 1050,
    "landed": "bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "ASML",
    "quarter": "Q1 2026",
    "date": "2026-04",
    "post": 1587,
    "landed": "base→bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "ASML",
    "quarter": "Q2 2026",
    "date": "2026-07",
    "post": 1815,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "AVGO",
    "quarter": "Q4 FY24",
    "date": "2024-11",
    "post": 185,
    "landed": "bull",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "AVGO",
    "quarter": "Q1 FY25",
    "date": "2025-02",
    "post": 228,
    "landed": "base→bull",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "AVGO",
    "quarter": "Q2 FY25",
    "date": "2025-05",
    "post": 242,
    "landed": "bear",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "AVGO",
    "quarter": "Q3 FY25",
    "date": "2025-08",
    "post": 298,
    "landed": "base→bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "AVGO",
    "quarter": "Q4 FY25",
    "date": "2025-11",
    "post": 368,
    "landed": "bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "AVGO",
    "quarter": "Q1 FY26",
    "date": "2026-02",
    "post": 460,
    "landed": "bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "AVGO",
    "quarter": "Q2 FY26",
    "date": "2026-06",
    "post": 387,
    "landed": "bear→base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "FICO",
    "quarter": "Q1 FY25",
    "date": "2025-01",
    "post": 1950,
    "landed": "base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "FICO",
    "quarter": "Q2 FY25",
    "date": "2025-04",
    "post": 1880,
    "landed": "base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "FICO",
    "quarter": "Q3 FY25",
    "date": "2025-07",
    "post": 1050,
    "landed": "bear",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "FICO",
    "quarter": "Q4 FY25",
    "date": "2025-11",
    "post": 1020,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "FICO",
    "quarter": "Q1 FY26",
    "date": "2026-01",
    "post": 950,
    "landed": "bear",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "FICO",
    "quarter": "Q2 FY26",
    "date": "2026-04",
    "post": 1278,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "GOOGL",
    "quarter": "Q4 2024",
    "date": "2025-02",
    "post": 202,
    "landed": "base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "GOOGL",
    "quarter": "Q1 2025",
    "date": "2025-04",
    "post": 177,
    "landed": "bear",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "GOOGL",
    "quarter": "Q2 2025",
    "date": "2025-07",
    "post": 168,
    "landed": "bear",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "GOOGL",
    "quarter": "Q3 2025",
    "date": "2025-10",
    "post": 196,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "GOOGL",
    "quarter": "Q4 2025",
    "date": "2026-02",
    "post": 258,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "GOOGL",
    "quarter": "Q1 2026",
    "date": "2026-04",
    "post": 375,
    "landed": "bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "META",
    "quarter": "Q4 2024",
    "date": "2025-01",
    "post": 690,
    "landed": "base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "META",
    "quarter": "Q1 2025",
    "date": "2025-04",
    "post": 600,
    "landed": "bear→base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "META",
    "quarter": "Q2 2025",
    "date": "2025-07",
    "post": 775,
    "landed": "bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "META",
    "quarter": "Q3 2025",
    "date": "2025-10",
    "post": 635,
    "landed": "bear",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "META",
    "quarter": "Q4 2025",
    "date": "2026-01",
    "post": 715,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "META",
    "quarter": "Q1 2026",
    "date": "2026-04",
    "post": 612,
    "landed": "bear",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MRVL",
    "quarter": "Q4 FY25",
    "date": "2025-02",
    "post": 70,
    "landed": "bear→base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "MRVL",
    "quarter": "Q1 FY26",
    "date": "2025-05",
    "post": 62,
    "landed": "bear",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MRVL",
    "quarter": "Q2 FY26",
    "date": "2025-08",
    "post": 82,
    "landed": "base→bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MRVL",
    "quarter": "Q3 FY26",
    "date": "2025-11",
    "post": 105,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MRVL",
    "quarter": "Q4 FY26",
    "date": "2026-02",
    "post": 122,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MRVL",
    "quarter": "Q1 FY27",
    "date": "2026-05",
    "post": 219,
    "landed": "bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MSFT",
    "quarter": "Q2 FY25",
    "date": "2025-01",
    "post": 418,
    "landed": "base→bull",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "MSFT",
    "quarter": "Q3 FY25",
    "date": "2025-04",
    "post": 388,
    "landed": "bear→base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "MSFT",
    "quarter": "Q4 FY25",
    "date": "2025-07",
    "post": 455,
    "landed": "base→bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MSFT",
    "quarter": "Q1 FY26",
    "date": "2025-10",
    "post": 535,
    "landed": "bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MSFT",
    "quarter": "Q2 FY26",
    "date": "2026-01",
    "post": 510,
    "landed": "base→bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MSFT",
    "quarter": "Q3 FY26",
    "date": "2026-04",
    "post": 441,
    "landed": "bear→base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MU",
    "quarter": "Q2 FY25",
    "date": "2025-03",
    "post": 108,
    "landed": "base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "MU",
    "quarter": "Q3 FY25",
    "date": "2025-06",
    "post": 112,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MU",
    "quarter": "Q4 FY25",
    "date": "2025-09",
    "post": 148,
    "landed": "base→bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MU",
    "quarter": "Q1 FY26",
    "date": "2025-12",
    "post": 340,
    "landed": "bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MU",
    "quarter": "Q2 FY26",
    "date": "2026-03",
    "post": 620,
    "landed": "bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "MU",
    "quarter": "Q3 FY26",
    "date": "2026-06",
    "post": 979,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "NVDA",
    "quarter": "Q3 FY25",
    "date": "2024-11",
    "post": 145,
    "landed": "base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "NVDA",
    "quarter": "Q4 FY25",
    "date": "2025-02",
    "post": 132,
    "landed": "bear→base",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "NVDA",
    "quarter": "Q1 FY26",
    "date": "2025-05",
    "post": 120,
    "landed": "bear",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "NVDA",
    "quarter": "Q2 FY26",
    "date": "2025-08",
    "post": 141,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "NVDA",
    "quarter": "Q3 FY26",
    "date": "2025-11",
    "post": 155,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "NVDA",
    "quarter": "Q4 FY26",
    "date": "2026-02",
    "post": 213,
    "landed": "base→bull",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "TSM",
    "quarter": "Q4 2024",
    "date": "2025-01",
    "post": 197,
    "landed": "base",
    "conf": "low",
    "bandHit": true
  },
  {
    "t": "TSM",
    "quarter": "Q1 2025",
    "date": "2025-04",
    "post": 166,
    "landed": "bear",
    "conf": "low",
    "bandHit": true
  },
  {
    "t": "TSM",
    "quarter": "Q2 2025",
    "date": "2025-07",
    "post": 226,
    "landed": "base→bull",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "TSM",
    "quarter": "Q3 2025",
    "date": "2025-10",
    "post": 279,
    "landed": "bull",
    "conf": "med",
    "bandHit": true
  },
  {
    "t": "TSM",
    "quarter": "Q4 2025",
    "date": "2026-01",
    "post": 304,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "TSM",
    "quarter": "Q1 2026",
    "date": "2026-04",
    "post": 338,
    "landed": "base",
    "conf": "high",
    "bandHit": true
  },
  {
    "t": "TSM",
    "quarter": "Q2 2026",
    "date": "2026-07",
    "post": 407,
    "landed": "bear→base",
    "conf": "med",
    "bandHit": true
  }
];

const PF_PREDICTIONS = {
  "ASML": {
    "quarter": "Q2 2026",
    "asOf": "2026-07-16",
    "case": "BASE",
    "note": "50%"
  },
  "AVGO": {
    "quarter": "Q2 FY2026",
    "asOf": "2026-06-06",
    "case": "BASE",
    "note": "probability tail toward BEAR elevated"
  },
  "MU": {
    "quarter": "Q3 FY2026",
    "asOf": "2026-07-11",
    "case": "BASE, tracking toward BULL on fundamentals",
    "note": ""
  },
  "TSM": {
    "quarter": "Q2 2026",
    "asOf": "2026-07-16",
    "case": "BASE",
    "note": "50%"
  }
};

// Graded transitions: rows where a PRIOR standing prediction has been checked against a
// LATER landed outcome. Hand-appended by the /scorecard skill, then PRESERVED by this
// script on every regeneration (it has no way to derive a grading decision on its own —
// see .claude/commands/scorecard.md). Each entry: { t, predictedAt, predictedCase,
// gradedQuarter, landed, matched }.
const PF_GRADED = [];
